language: node_js
node_js:
  - "node"

dist: trusty
sudo: required

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run lint
  - npm run build

before_deploy:
  - rm .gitignore
  - ls -a
  - cd lib
  - ls -a
  - cd ../

deploy:
  provider: npm
  email: $email
  api_key: $api_key
  on:
    branches: master

after_deploy:
  - ls -a
  - cd lib
  - ls -a
  - cd ../

branches:
  only:
    - master
