language: node_js
node_js:
  - "node"

dist: trusty
sudo: required

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run lint
  - npm run build

deploy:
  provider: npm
  email: $email
  api_key: $api_key
  on:
    branches: master

branches:
  only:
    - master
